[package]
name = "sknpm"
version = "0.1.0"

[dependencies]
skargo = { path = "../skargo" }
skbuild = { path = "../skbuild" }
semver = { path = "../semver" }

[dev-dependencies]
sktest = { path = "../sktest" }

[build-dependencies]
skbuild = { path = "../skbuild" }

[[bin]]
name = "sknpm"
main = "Sknpm.main"
